apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: db-dep-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-dep
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 20
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: 200Mi