apiVersion: v1
kind: PersistentVolume
metadata:
  name: psqlpv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain     #1/ Recycle  delete hostpath    # Delete (for deleteing external disk like ebs) # Retain (keep)
  hostPath:
    path: "/home/omkar/Documents/Other/swapnil_app/angular-python-flask-demo/Volumes"