apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  ports:
    - targetPort: 5432
      nodePort: 30008
      port: 5432

  # type: ClusterIP
  # ports:
  #   - targetPort: 80
  #     port: 80

  # type: LoadBalancer
  # ports:
  #   - targetPort: 80
  #     port: 80

  selector:
    type: db-type-pod